#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running lint check..."
pnpm run lint

echo "Running project cleanup..."
pnpm run project:cleanup

echo "Generating documentation index..."
pnpm run docs:generate-index

# Run successful message
echo "Pre-commit checks passed. To find duplicate documentation, run 'pnpm run docs:find-duplicates'." 