   name: Deploy to Production

   on:
     push:
       tags:
         - 'v*'

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - uses: pnpm/action-setup@v2
           with:
             version: 8
         - uses: actions/setup-node@v3
           with:
             node-version: 18
             cache: 'pnpm'
         - name: Install dependencies
           run: pnpm install
         - name: Build
           run: pnpm build
         - name: Deploy to Firebase
           uses: FirebaseExtended/action-hosting-deploy@v0
           with:
             repoToken: '${{ secrets.GITHUB_TOKEN }}'
             firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
             projectId: autonomy-heroes
             channelId: live