name: Deploy to Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        
      - name: Lint
        run: pnpm lint || echo "Linting issues found, but continuing"
        
      - name: Find documentation duplicates
        run: pnpm run docs:find-duplicates || echo "Documentation issues found, but continuing"
      
      - name: Verify firebase.json
        run: npx -y firebase-tools deploy --dry-run --json || echo "Verification issues found, but continuing"
  
  build_and_deploy:
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        
      - name: Project cleanup
        run: pnpm run project:cleanup
        
      - name: Build common package
        run: |
          cd packages/common
          pnpm run build

      - name: Build admin app
        if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'deploy-admin')
        run: |
          cd packages/admin
          pnpm run build
          
      - name: Build hours app
        if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'deploy-hours')
        run: |
          cd packages/hours
          pnpm run build
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/266526530869/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@autonomy-heroes.iam.gserviceaccount.com'
          
      - name: Deploy to Firebase
        if: github.event_name == 'push'
        run: |
          npm install -g firebase-tools
          firebase deploy || echo "Deployment issues found, but continuing for now"
          
      - name: Deploy PR Preview
        if: github.event_name == 'pull_request'
        run: |
          npm install -g firebase-tools
          firebase hosting:channel:deploy pr-${{ github.event.pull_request.number }} 